site_name: 'Імпульсний перетворювач катодного захисту ІПКЗ'
site_url: https://data.texnotek.com
#site_url: https://dialmak.github.io/site_ipkz
site_author: 'Остапчук Віктор'
copyright: Ostapchuk Viktor &copy; 2025 
dev_addr: '127.0.0.1:8000'
theme:
#  font:
#    text: Cabin Condensed
  icon:
    logo: material/home-lightning-bolt
    favicon: ./assets/images/favicon.png
  features:
#     - navigation.footer
     - navigation.tracking
     - navigation.sections
#     - navigation.indexes
     - toc.integrate
     - navigation.top
  name: material
  language: uk
  palette: 


    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/lightbulb
        name: Темна тема

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/lightbulb-outline
        name: Світла тема

extra_css:
  - ./assets/stylesheets/extra.css

plugins:
    - awesome-pages:
        collapse_single_pages: false
    - search:
        separator: '[\s\-\.]+'
        lang:
          - en
          - uk
    - minify:
        minify_html: false 
    - glightbox:
        touchNavigation: true
        loop: false
        effect: zoom
        slide_effect: slide
        width: 100%
        height: auto
        zoomable: true
        draggable: true
        skip_classes:
          - custom-skip-class-name
        auto_caption: true
        caption_position: bottom
        background: none
        shadow: true
        manual: false     

watch:
  - includes

markdown_extensions:
  - abbr
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - def_list
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.snippets:
      auto_append:
        - includes/abbreviations.md
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg        
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  
extra:
  generator: false
  social:
    - icon: fontawesome/solid/paper-plane
      link: mailto:<ostap@texnotek.com>

